### ISSUE TITLE
Cleanup for v1

### ISSUE THREAD

**Issue by wdower** [mitre/saf-site-frontend#57]
- [x] in the "Toolkit" modal:
    - [X] remove "Our tools"
    - [x] ensure Normalize, Plan, Visualize links go somewhere once we have those pages built (#49 #50 #51)
    - [X] Remove "Watch Demo" and "Contact Us"
- [X] in the "More" modal:
    - [X] fix "Help Center" to "FAQ" as per #47 
    - [X] Remove "Events"
    - [X] Remove "Recent Posts" and everything else on down
- [x] Revamp mobile nav view
    - [X]  Remove "Our Tools"
    - [x] Add necessary nav links
- [x] Move inline svg to asset (Check for more than github and saf)
    - [x] Take out png or jpeg versions of logos where needed 
- [x] Change nav link color when on active page
- [X] Fix view details table for validate and harden (Discussed in comment by Will in #42 )
- [x] Make slugify a utility function or import library to clean code (Addressed in #29 )
- [x] Add copyright logo to MITRE SAF (i.e. "MITRE SAF" should be "MITRE SAF©" and "MITRE Security Automation Framework" should be "MITRE Security Automation Framework©")
- [x] Start migration from Vue 2 script to Vue 3 script

**Comment by wdower** [comment]
- [ ] Add copyright logo to MITRE SAF

i.e. "MITRE SAF" should be "MITRE SAF©" and "MITRE Security Automation Framework" should be "MITRE Security Automation Framework©"

(fun fact, you can type the copyright symbol by pressing OPT + G on macOS)

This topic came up when management reviewed the existing site. Might as well do it correctly from the jump on this version.

**Comment by ChrisHinchey** [comment]
For "ensure Normalize, Plan, Visualize links go somewhere once we have those pages built (https://github.com/mitre/saf-site-frontend/issues/49 https://github.com/mitre/saf-site-frontend/issues/50 https://github.com/mitre/saf-site-frontend/issues/51)" I have added placeholder pages for now in #63
