### ISSUE TITLE
Site Roadmap

### ISSUE THREAD

**Issue by GavMason** [mitre/saf-site-frontend#7]
### This is the progress of what has been done and what is next in line for implementation 

**NOTE: This is progress for the frontend and backend!**

- [x]  Created Strapi CMS (Content Management System) project to create database and generated endpoints
- [x]  Designed backend architecture to replicate the use cases for the current site and cater to new features using Strapi content types  
- [x] Created Nuxt 3 (Vue 3/Vite) project for the Frontend 
- [x] Enable backend and frontend to utilized GraphQL for query based API calls
- [x] Designed header
- [x] Set frame of reference for spacing on the site
- [x] Created static 404 exception page
- [x] Create a markdown renderer in a Strapi controller in order to get HTML which can be styled on the frontend with Tailwind Typography plugin. See this related [issue](https://github.com/mitre/saf-site-nuxt/issues/4)
- [x] Style blog content using Tailwind Typography 
- [ ] Add search bar for blog posts. See related [issue](https://github.com/mitre/saf-site-nuxt/issues/8)
- [ ] Update tags in blog posts. See this related [issue](https://github.com/mitre/saf-site-nuxt/issues/6)
- [x] Finish populating the database with the data from json files of the old site. Verify that the current schema is appropriate for our use cases to save time updating entries later down the road.
- [x] Create documentation page 
- [ ] Create landing page (Aaron, Eugene, and Emily have good ideas for what we want conceptionally)
- [x] Add Netlify support to better comunciate project updates to the team via demos. See this related [issue](https://github.com/mitre/saf-site-nuxt/issues/2)
